url: https://https://zolanda-popov.github.io/
baseurl: /super-sus-casino-website/

# Site settings
title: The Super Sus Casino
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Garth Makoldo
  pic: a1ien
  position: Region Manager

- name: Zolada Popov
  pic: 2olada
  position: Lead Marketer

- name: Chet Apichart
  pic: ch3t
  position: Brand Ambassador
  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/_therealzoladapopoy_/
  - title: github
    url: https://github.com/zolanda-popov/super-sus-casino-website


# Build settings
markdown: kramdown
permalink: pretty
